FROM golang:1.25.5 AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /bin/worker ./cmd/worker

FROM alpine:3.20
RUN apk add --no-cache ca-certificates bash
WORKDIR /
COPY --from=builder /bin/worker /worker
ENV WORKER_CONCURRENCY=4
ENV WORKER_HTTP_TIMEOUT_SECONDS=10
ENTRYPOINT ["/worker"]
