FROM golang:1.25.5 AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /bin/api ./cmd/api

FROM gcr.io/distroless/static:nonroot
WORKDIR /
COPY --from=builder /bin/api /api
USER nonroot:nonroot
ENV HTTP_ADDR=:8090
ENTRYPOINT ["/api"]
