services:
  redis:
    image: redis:7
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 2s
      retries: 20
    networks: [dtsnet]

  api:
    user: "0:0"
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      REDIS_ADDR: redis:6379
      DATA_DIR: /data
      HTTP_ADDR: :8090
      TASKS_RATE_LIMIT: "100000"
      TASKS_RATE_WINDOW_SECONDS: "10"
    ports:
      - "8090:8090"
    volumes:
      - dts_data:/data
    depends_on:
      redis:
        condition: service_healthy
    restart: on-failure
    networks: [dtsnet]

  worker:
    user: "0:0"
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      REDIS_ADDR: redis:6379
      DATA_DIR: /data
      API_BASE_URL: http://api:8090
      WORKER_CONCURRENCY: "4"
    volumes:
      - dts_data:/data
    depends_on:
      redis:
        condition: service_healthy
      api:
        condition: service_started
    restart: on-failure
    networks: [dtsnet]

networks:
  dtsnet:

volumes:
  dts_data:
